
public static void evenFibonacciNumbers(){
 
	//find the sum of all the even fibonacci numbers below 4_000_000
	
	//fibonacci numbers are generated by adding the previous two values
	//in the sequence
	
	//only add even numbers
	
	//max value is 4_000_000
	
	int maxValue = 4_000_000;
	int previousValue = 1;
	int currentValue = 2;
	int sum = 0;
	
	while(currentValue <= maxValue){
		
		if(currentValue % 2 == 0){
			sum += currentValue;
		}
		
		// get current value prior to it changing so it can be 
		// set a previous value
		int tempCurrentValue = currentValue;
		
		currentValue += previousValue;
		previousValue = tempCurrentValue;
	}
	
	System.out.println(sum);
}


    
   

